# Generated by Django 6.0.4 on 2026-04-30 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('sala', 'Sala'), ('cantina', 'Cantina'), ('sala_direcao', 'Sala Direcao'), ('biblioteca', 'Biblioteca'), ('laboratorio', 'Laboratório'), ('auditorio', 'Auditório'), ('diretoria', 'Diretoria'), ('quadras', 'Quadras')], max_length=20, verbose_name='Nome')),
                ('nomenclatura', models.CharField(help_text='nomenclatura do ambiente', max_length=70, unique=True, verbose_name='nomenclatura')),
                ('exclusividade', models.CharField(choices=[('exclusivas', 'Exclusivas'), ('comunitarias', 'Comunitarias')], max_length=20, verbose_name='exclusividade')),
                ('bloco', models.ForeignKey(blank=True, help_text='Nome do bloco', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='blocos.bloco', verbose_name='Bloco')),
            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
            },
        ),
    ]
