# Generated by Django 6.0.3 on 2026-04-04 23:02

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do ambiente', max_length=70, verbose_name='Nome')),
                ('nomenclatura', models.CharField(help_text='nomenclatura do usuario', max_length=70, verbose_name='nomenclatura')),
                ('exclusividade', models.CharField(help_text='exclusividade do Usuario', max_length=70, verbose_name='exclusividade')),
                ('bloco', models.ForeignKey(help_text='Nome do Bloco', on_delete=django.db.models.deletion.CASCADE, related_name='bloco',to='blocos.bloco',verbose_name='Bloco'
                )),

            ],
            options={
                'verbose_name': 'Ambiente',
                'verbose_name_plural': 'Ambientes',
            },
        ),
    ]
