# Generated by Django 6.0.4 on 2026-05-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='acesso_permitido',
            field=models.CharField(choices=[('todos', 'Todos'), ('secretaria', 'Secretaria'), ('inspetor', 'Inspetor'), ('professor', 'Professor')], default='', max_length=20, verbose_name=' Acesso Permitido '),
            preserve_default=False,
        ),
    ]
