# Generated by Django 6.0.4 on 2026-04-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='exclusividade',
            field=models.CharField(help_text='exclusividade do ambiente', max_length=70, verbose_name='exclusividade'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='nomenclatura',
            field=models.CharField(help_text='nomenclatura do ambiente', max_length=70, verbose_name='nomenclatura'),
        ),
    ]
