# Generated by Django 6.0.4 on 2026-04-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0002_alter_ambiente_exclusividade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='exclusividade',
            field=models.CharField(choices=[('exclusivas', 'Exclusivas'), ('comunitarias', 'Comunitarias')], max_length=70, verbose_name='exclusividade'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='nome',
            field=models.CharField(choices=[('sala', 'Sala'), ('bloco', 'Bloco'), ('cantina', 'Cantina'), ('sala_direcao', 'Sala Direcao')], max_length=70, verbose_name='Nome'),
        ),
    ]
