# Generated by Django 6.0.4 on 2026-04-15 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0003_alter_ambiente_exclusividade_alter_ambiente_nome'),
        ('blocos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='bloco',
            field=models.ForeignKey(blank=True, help_text='Nome do bloco', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='blocos.bloco', verbose_name='Bloco'),
        ),
    ]
