# Generated by Django 6.0.4 on 2026-04-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0004_ambiente_bloco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='nome',
            field=models.CharField(choices=[('sala', 'Sala'), ('cantina', 'Cantina'), ('sala_direcao', 'Sala Direcao'), ('biblioteca', 'Biblioteca'), ('laboratorio', 'Laboratório'), ('auditorio', 'Auditório'), ('diretoria', 'Diretoria'), ('quadras', 'Quadras')], max_length=70, verbose_name='Nome'),
        ),
    ]
