# Generated by Django 6.0.4 on 2026-04-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0006_alter_ambiente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='nome',
            field=models.CharField(choices=[('sala', 'Sala'), ('cantina', 'Cantina'), ('sala_direcao', 'Sala Direcao'), ('biblioteca', 'Biblioteca'), ('laboratorio', 'Laboratório'), ('auditorio', 'Auditório'), ('diretoria', 'Diretoria'), ('quadras', 'Quadras')], max_length=70, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='nomenclatura',
            field=models.CharField(help_text='nomenclatura do ambiente', max_length=70, unique=True, verbose_name='nomenclatura'),
        ),
    ]
