# Generated by Django 6.0.4 on 2026-04-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0008_alter_ambiente_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='exclusividade',
            field=models.CharField(choices=[('exclusivas', 'Exclusivas'), ('comunitarias', 'Comunitarias')], max_length=20, verbose_name='exclusividade'),
        ),
    ]
