# Generated by Django 6.0.4 on 2026-05-14 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='data_prevista',
            new_name='datahora_prevista',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='hora_prevista',
        ),
    ]
