# Generated by Django 6.0.4 on 2026-05-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_prevista',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Prevista de Retirada'),
        ),
    ]
