# Generated by Django 6.0.4 on 2026-05-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_rename_data_prevista_reserva_datahora_prevista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='datahora_prevista',
            field=models.DateTimeField(verbose_name='Data e hora Prevista de Uso'),
        ),
    ]
