# Generated by Django 6.0.4 on 2026-05-07 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copia_chave', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data Criação')),
                ('data_prevista', models.DateField(verbose_name='Data Prevista')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data Devolução')),
                ('hora', models.TimeField(verbose_name='Hora de Retirada')),
                ('hora_prevista', models.TimeField(verbose_name='Hora Prevista de Devolução')),
                ('hora_devolucao', models.TimeField(blank=True, null=True, verbose_name='Hora de Devolução')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('emprestada', 'Emprestada'), ('reservada', 'Reservada'), ('manutencao', 'Manutenção'), ('perdida', 'Perdida')], max_length=70, verbose_name='Status')),
                ('copias_chave', models.ManyToManyField(related_name='emprestimos', to='copia_chave.copiachave', verbose_name='Cópias das Chaves')),
                ('entregue_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_entregues', to='usuarios.usuario', verbose_name='Entregue por')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='usuarios.usuario', verbose_name='Quem retirou')),
                ('recebido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_recebidos', to='usuarios.usuario', verbose_name='Recebido por')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
            },
        ),
    ]
