# Generated by Django 6.0.4 on 2026-04-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa', models.CharField(max_length=100, verbose_name='Pessoa')),
                ('data_criacao', models.DateField(help_text='Data da criação do emprestimo', verbose_name='Data Criação')),
                ('data_prevista', models.DateField(help_text='Data da prevista do emprestimo', verbose_name='Data Prevista')),
                ('data_devolucao', models.DateField(help_text='Data de Devolução do emprestimo', verbose_name='Data Prevista')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('emprestada', 'Emprestada'), ('reservada', 'Reservada'), ('manutencao', 'Manutenção'), ('perdida', 'Perdida')], max_length=70, verbose_name='Status')),
                ('hora', models.TimeField(help_text='Hora do emprestimo', verbose_name='Hora')),
            ],
            options={
                'verbose_name': 'emprestimo',
                'verbose_name_plural': 'emprestimos',
            },
        ),
    ]
