# Generated by Django 6.0.4 on 2026-05-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copia_chave', '0001_initial'),
        ('emprestimo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='copia_chave',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='copias_chave',
            field=models.ManyToManyField(related_name='emprestimos', to='copia_chave.copiachave', verbose_name='Cópias das Chaves'),
        ),
    ]
