# Generated by Django 6.0.4 on 2026-05-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='email_atraso',
            field=models.BooleanField(default=False),
        ),
    ]
