# Generated by Django 6.0.4 on 2026-05-27 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprestimo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='entregue_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_entregues', to=settings.AUTH_USER_MODEL, verbose_name='Entregue por'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to=settings.AUTH_USER_MODEL, verbose_name='Quem retirou'),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='recebido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emprestimos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por'),
        ),
    ]
