# Generated by Django 6.0.4 on 2026-05-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('emprestada', 'Emprestada'), ('reservada', 'Reservada'), ('manutencao', 'Manutenção'), ('perdida', 'Perdida'), ('devolvido', 'Devolvido')], max_length=70, verbose_name='Status'),
        ),
    ]
