# Generated by Django 6.0.4 on 2026-06-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('emprestada', 'Emprestada'), ('reservada', 'Reservada'), ('manutencao', 'Manutenção'), ('danificada', 'Danificada'), ('perdida', 'Perdida'), ('pendente', 'Pendente'), ('devolvido', 'Devolvido')], max_length=70, verbose_name='Status'),
        ),
    ]
