# Generated by Django 6.0.4 on 2026-06-15 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copia_chave', '0003_rename_horarario_devolucao_copiachave_horario_devolucao'),
        ('emprestimo', '0003_alter_emprestimo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmprestimoCopiaChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_devolucao', models.TimeField(blank=True, null=True, verbose_name='harario de devolucao')),
                ('copia_chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copia_chave.copiachave', verbose_name='Chaves')),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimo.emprestimo', verbose_name='Emprestimo')),
            ],
            options={
                'verbose_name': 'Chave de Emprestimo',
                'verbose_name_plural': 'Chaves de Emprestimos',
            },
        ),
    ]
