# Generated by Django 6.0.4 on 2026-05-07 22:19

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do usuario', max_length=70, verbose_name='Nome')),
                ('email', models.CharField(help_text='Email do usuario', max_length=70, unique=True, verbose_name='Email')),
                ('senha', models.CharField(help_text='senha do Fornecedor', max_length=70, verbose_name='Senha')),
                ('tipoUsuario', models.CharField(choices=[('secretaria', 'Secretaria'), ('inspetor', 'Inspetor Escolar'), ('professor', 'Professor')], default='secretaria', max_length=70, verbose_name='tipoUsuario')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='usuarios', variations={}, verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='InspesorEscolar',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Inspetor Escolar',
                'verbose_name_plural': 'Inspetores Escolares',
            },
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
            },
            bases=('usuarios.usuario',),
        ),
    ]
