# Generated by Django 6.0.3 on 2026-03-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do usuario', max_length=70, verbose_name='Nome')),
                ('email', models.CharField(help_text='Email do usuario', max_length=70, unique=True, verbose_name='Email')),
                ('senha', models.CharField(help_text='senha do Fornecedor', max_length=70, verbose_name='Senha')),
                ('tipoUsuario', models.CharField(help_text='Tipo do Usuario', max_length=70, verbose_name='tipoUsuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
