# Generated by Django 6.0.4 on 2026-04-30 02:36

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspesorEscolar',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Inspetor Escolar',
                'verbose_name_plural': 'Inspetores Escolares',
            },
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
            },
            bases=('usuarios.usuario',),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, upload_to='usuarios', variations={}, verbose_name='Foto'),
        ),
    ]
