# Generated by Django 6.0.4 on 2026-05-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='nome',
            field=models.CharField(default='', max_length=70, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
