# Generated by Django 6.0.4 on 2026-05-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_ate',
            field=models.DateField(blank=True, null=True, verbose_name='Bloqueado até'),
        ),
    ]
