# Generated by Django 6.0.4 on 2026-06-06 13:28

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuariopersonalizado_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspetor',
            fields=[
            ],
            options={
                'verbose_name': 'Inspetor',
                'verbose_name_plural': 'Inspetores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.usuariopersonalizado',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.usuariopersonalizado',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.usuariopersonalizado',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
