# Generated by Django 6.0.4 on 2026-04-29 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopiaChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Identificador único da cópia', max_length=50, unique=True, verbose_name='Identificador')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('emprestada', 'Emprestada'), ('reservada', 'Reservada'), ('manutencao', 'Manutenção'), ('perdida', 'Perdida')], max_length=20)),
                ('chave', models.ForeignKey(help_text='Chave associada', on_delete=django.db.models.deletion.CASCADE, related_name='copias', to='chaves.chave', verbose_name='Chave')),
            ],
            options={
                'verbose_name': 'Cópia de Chave',
                'verbose_name_plural': 'Cópias de Chaves',
            },
        ),
    ]
