# Generated by Django 6.0.4 on 2026-06-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copia_chave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copiachave',
            name='horarario_devolucao',
            field=models.TimeField(blank=True, null=True, verbose_name='hora de cada devolucao'),
        ),
    ]
