# Generated by Django 6.0.4 on 2026-05-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copia_chave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copiachave',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('emprestada', 'Emprestada'), ('reservada', 'Reservada'), ('manutencao', 'Manutenção'), ('perdida', 'Perdida'), ('danificada', 'Danificada')], max_length=20),
        ),
    ]
