# Generated by Django 6.0.4 on 2026-05-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copia_chave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copiachave',
            name='identificador',
        ),
    ]
