# Generated by Django 6.0.4 on 2026-05-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copia_chave', '0002_remove_copiachave_identificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='copiachave',
            name='identificador',
            field=models.CharField(blank=True, help_text='Identificador único da cópia', max_length=50, null=True, unique=True, verbose_name='Identificador'),
        ),
    ]
