# Generated by Django 6.0.4 on 2026-06-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copia_chave', '0002_copiachave_horarario_devolucao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copiachave',
            old_name='horarario_devolucao',
            new_name='horario_devolucao',
        ),
    ]
