# Generated by Django 6.0.4 on 2026-04-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Nome da Chave', max_length=70, verbose_name='Descrição:')),
                ('codigo_indentificacao', models.IntegerField(help_text='Codigo da Chave', max_length=70, unique=True, verbose_name='Codigo Indentificador')),
                ('status', models.CharField(help_text='Status do da chave', max_length=70, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
            },
        ),
    ]
