# Generated by Django 6.0.4 on 2026-05-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambiente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Nome da Chave', max_length=70, verbose_name='Descrição:')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('manutencao', 'Manutenção'), ('perdida', 'Perdida')], max_length=70, verbose_name='Status')),
                ('tipo', models.CharField(choices=[('comum', 'Comum'), ('mestra', 'Mestra')], default='comum', max_length=20, verbose_name='Tipo')),
                ('ambientes', models.ManyToManyField(blank=True, related_name='chaves', to='ambiente.ambiente')),
            ],
            options={
                'verbose_name': 'Chave',
                'verbose_name_plural': 'Chaves',
            },
        ),
    ]
