# Generated by Django 6.0.4 on 2026-05-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('manutencao', 'Manutenção'), ('perdida', 'Perdida'), ('danificada', 'Danificada')], max_length=70, verbose_name='Status'),
        ),
    ]
