# Generated by Django 6.0.4 on 2026-04-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='codigo_indentificacao',
            field=models.IntegerField(help_text='Codigo da Chave', max_length=70, unique=True, verbose_name='Codigo Indentificador'),
        ),
        migrations.AlterField(
            model_name='chave',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('emprestada', 'Emprestada'), ('reservada', 'Reservada'), ('manutencao', 'Manutenção'), ('perdida', 'Perdida')], max_length=70, verbose_name='Status'),
        ),
    ]
