# Generated by Django 6.0.4 on 2026-05-25 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocos', '0001_initial'),
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='bloco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chaves', to='blocos.bloco'),
        ),
    ]
