# Generated by Django 6.0.4 on 2026-06-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='tipo',
            field=models.CharField(choices=[('comum', 'Comum'), ('mestraBloco', 'Mestra Bloco'), ('mestra', 'Mestra')], default='comum', max_length=20, verbose_name='Tipo'),
        ),
    ]
