# Generated by Django 6.0.4 on 2026-04-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0002_alter_chave_codigo_indentificacao_alter_chave_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='codigo_indentificacao',
            field=models.IntegerField(help_text='Codigo da Chave', unique=True, verbose_name='Codigo Indentificador'),
        ),
    ]
