# Generated by Django 6.0.4 on 2026-04-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0003_alter_chave_codigo_indentificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chave',
            name='id',
        ),
        migrations.AlterField(
            model_name='chave',
            name='codigo_indentificacao',
            field=models.IntegerField(help_text='Codigo da Chave', primary_key=True, serialize=False, verbose_name='Codigo Indentificador'),
        ),
    ]
