# Generated by Django 6.0.4 on 2026-04-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0004_remove_chave_id_alter_chave_codigo_indentificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chave',
            name='codigo_indentificacao',
        ),
        migrations.AddField(
            model_name='chave',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
