# Generated by Django 6.0.4 on 2026-04-23 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0007_alter_ambiente_nome_alter_ambiente_nomenclatura'),
        ('chaves', '0005_remove_chave_codigo_indentificacao_chave_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chaves', to='ambiente.ambiente'),
        ),
        migrations.AlterField(
            model_name='chave',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('manutencao', 'Manutenção'), ('perdida', 'Perdida')], max_length=70, verbose_name='Status'),
        ),
    ]
