# Generated by Django 6.0.4 on 2026-04-23 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocos', '0002_alter_bloco_quantidade'),
        ('chaves', '0006_chave_ambiente_alter_chave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='bloco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='blocos.bloco'),
        ),
    ]
