# Generated by Django 6.0.4 on 2026-04-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0007_alter_ambiente_nome_alter_ambiente_nomenclatura'),
        ('chaves', '0007_chave_bloco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chave',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='chave',
            name='bloco',
        ),
        migrations.AddField(
            model_name='chave',
            name='ambientes',
            field=models.ManyToManyField(blank=True, related_name='chaves', to='ambiente.ambiente'),
        ),
    ]
